### ISSUE TITLE
Release 3

### ISSUE THREAD

**Issue by theaspect** [OrdinarySkalen/GoodlineRep#3]
1. Обновить README
2. Убрать лог из репозитория
3. Странная организация кода: классы лежат в папках но строки package в классах нет. Нужно привести в порядок. Плюс в папке (не пакете!) Domain лежит все подряд. Что такое Доменный класс? Напиши в комментарии к таске.
4. Требование 3.8 не выполнено – исправить везде
5. Логгер умеет сам форматировать строку – исправить везде
6. Исправь везде перенос `) {` на новую строку – это глюк идеи

**Comment by OrdinarySkalen** [comment]
Домменный класс - класс приложения, отвечающий за отображение предметной области, как правило не содержит какие либо сложные методы описывающие бизнесс логику, в данном случае доменными классами являются Accounting, Resource, User, Roles.
